# Generated by Django 4.1.7 on 2023-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("univ", models.CharField(max_length=20)),
                ("clean", models.FloatField()),
                ("bad", models.FloatField()),
                ("region", models.FloatField()),
                ("minority", models.FloatField()),
                ("race", models.FloatField()),
                ("woman", models.FloatField()),
                ("man", models.FloatField()),
                ("age", models.FloatField()),
                ("religion", models.FloatField()),
                ("etc_hatred", models.FloatField()),
            ],
        ),
    ]
